name: My Videos
favicon: null
layout_spectrum: 0.6799084339290857
typography_spectrum: 0.7401859674137086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5123649842571467
  lightness: 0.04756276239641011
  saturation: 0.6774321971461177
  rhythmicContrast: 0.06154511822387576
purpose: []
